images:
  roundel: https://raw.githubusercontent.com/tudublinesports/PixelShift/master/assets/logos/tudesports.svg
  embed: https://raw.githubusercontent.com/tudublinesports/PixelShift/master/assets/logos/roundel.png
society:
  name: Esports Soc
  tagline: TU Dublin's Esports Society.
navigation:
  blog:
    - text: Events
      tag: events
    - text: Admin Blog
      tag: admins
    - text: Newsletters
      tag: newsletter
  buttons:
    primary:
      text: Sign Up!
      link: https://join.tudublinesports.ie
    secondary:
      text: Discord
      link: https://discord.tudublinesports.ie/
drawer: navigation
home:
  hero:
    title:
      secondary: TU Dublin's Esports Society.
      primary: Join us today!
    body: Esports Soc was founded in 2019 with a goal to connect competitive students with others and compete against other colleges.
    buttons:
      primary:
        text: Sign Up!
        link: https://join.tudublinesports.ie
        aria: Link to the Clubs and Socs portal to join the society!
      secondary:
        link: https://instagram.com/tudublinesports
        aria: Link to our Instagram page!
      tertiary:
        link: https://discord.tudublinesports.ie/
        aria: Link to our Discord server!
  cta:
    title: Don't Miss Out!
    body: Esports Soc runs events of all kinds, helps to find teams for tournaments and expand your teamwork and skills within your games of choice while making (hopefully!) lifelong friends.
    button:
      text: Sign Up Today!
      link: https://join.tudublinesports.ie
  committee:
    - name: David Corcoran
      position: 🪑 Chair
      username: Arcane
      image: /assets/img/committee/david.webp
    - name: Polina
      position: 🪑 Vice-Chair
      username: /!polinchik
      image: /assets/img/
    - name: Ridwan
      position: 💌 Secretary
      username: MongolianYeti
      image: /assets/img/
    - name: Oludemilade
      position: 💸 Treasurer
      username: Demii
      image: /assets/img/committee/
    - name: 
      position: 📢 PRO
      username: 
      image: /assets/img/committee/
    - name: Juliet 
      position: 👩‍⚕️ HSO
      username: juliet
      image: /assets/img/committee/
    - name: Henry
      position: 🗺️ Bolton Rep
      username: 
      image: /assets/img/committee/
    - name: Ryan McCarthy
      position: 🗺️ Blanch Rep
      username: McCar
      image: /assets/img/committee/
    - name: 
      position: ♟️ Chess Rep
      username: BigCheeseDerv
      image: /assets/img/committee/
    - name: Ana
      position: 💻 Melty & Osu! Rep
      username: ana_rchy
      image: /assets/img/committee/ana.gif
    - name: Michaɫ Kos Sliwinski
      position: 🎮 LoL Rep
      username: Mitcha
      image: /assets/img/committee/
    - name: Brevin Monks
      position: 🚘 Mario Kart Rep
      username: Brevinthehouse
      image: /assets/img/committee/
    - name: Shane
      position: 🪖 CS2 Rep
      username: Dusty
      image: /assets/img/committee/
    - name: 
      position: ⚽ Rocket League Rep
      username: 
      image: /assets/img/committee/
    - name: 
      position: 💣 Valorant Rep
      username: Ruuzi
      image: /assets/img/committee/
    - name: Luna Henry
      position: 🎨 Splatoon Rep
      username: Wassuppeas
      image: /assets/img/committee/
    - name: 
      position: 👼 Overwatch & Tallaght Rep
      username: Nacho
      image: /assets/img/committee/
    - name:
      position: 🧱 R6 Siege Rep
      username: Skye
      image: /assets/img/committee/
    - name: Sam Carolan
      position: ♟️ TFT Rep
      username: Ubh
      image: /assets/img/committee/
    
    - name: Calvin
      position: 🍄 Smash Rep
      username: Foggy
      image: /assets/img/committee/
    - name: Nikita Sosnars
      position: 🏎️ Forza & Halo Rep
      username: insidesaturn8
      image: /assets/img/committee/
    - name:
      position: GCM
      username: King
      image: /assets/img/committee/
    - name:
      position: GCM
      username:
      image: /assets/img/committee/
    - name:
      position: GCM
      username: 
      image: /assets/img/committee/
    - name:
      position: GCM
      username:
      image: /assets/img/committee/
    - name:
      position: 
      username: 
      image: /assets/img/committee/
    - name:
      position:
      username:
      image: /assets/img/committee/
  sponsors:
footer:
  - credit: Powered by Redbrick's Atlas System
  - credit: (Special thanks to CS++)
